### ISSUE TITLE
Figuring out how to display the specific post's information, formatting, etc

### ISSUE THREAD

**Issue by VagishVela** [Perceptive-Porcupines/Perceptive-Porcupines-Code-Jam-8#1]

**Comment by VagishVela** [comment]
https://github.com/willmcgugan/textual/blob/main/examples/simple.py

**Comment by mustafaquraish** [comment]
#29 Adds some initial progress by rendering the answers in Markdown format, but work still needs to be done. Please see the pull request for details.

I'm not going to be working on this anymore (for the time being), so if anyone is interested in taking this up please go ahead.

**Comment by mustafaquraish** [comment]
I think we've come to reasonable ways to pass information around, so I'm closing this for now
