### ISSUE TITLE
Exit the program if someone runs `pytui example/runs_with_error.py` but there are no errors

### ISSUE THREAD

**Issue by VagishVela** [Perceptive-Porcupines/Perceptive-Porcupines-Code-Jam-8#15]

**Comment by ethansocal** [comment]
Maybe instead of stopping the program, we could show pylint or some other linter's errors. Not sure if that would be too ambitious or not.

**Comment by mustafaquraish** [comment]
With #23 we can just check if the `run_and_get_stderr()` returns an empty string, and then exit.

**Comment by VagishVela** [comment]
@mustafaquraish Does your PR #30 fix this as well?

**Comment by mustafaquraish** [comment]
> @mustafaquraish Does your PR #30 fix this as well?

Not my PR, can't comment on this. Exiting is a bit annoying if we are opening the display, simply calling `exit()` does not work in this context.

**Comment by mustafaquraish** [comment]
This seems to have already been implemented. No display is opened if there's no error.
