### ISSUE TITLE
Determine source of ResourceWarning

### ISSUE THREAD

**Issue by briancohan** [Perceptive-Porcupines/Perceptive-Porcupines-Code-Jam-8#59]
Every time I run the app, this error is left in my terminal

```
/usr/lib/python3.9/asyncio/base_events.py:681: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
  _warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by mustafaquraish** [comment]
That's because `StackOverflowFinder` created a requests session but never closes it. This can probably be fixed by not creating the session in `__init__()` anymore. I believe now we just compute the results once upfront anyway, so we can just create the session object in `search()` at the start, and then close it at the end of the function. This should get rid of the error

**Comment by briancohan** [comment]
> That's because `StackOverflowFinder` created a requests session but never closes it. This can probably be fixed by not creating the session in `__init__()` anymore. I believe now we just compute the results once upfront anyway, so we can just create the session object in `search()` at the start, and then close it at the end of the function. This should get rid of the error

I don't see the error when I use the `-n` flag. That implies that it's coming from `textual` not `StackOverflowFinder`

**Comment by mustafaquraish** [comment]
> I don't see the error when I use the `-n` flag. That implies that it's coming from `textual` not `StackOverflowFinder`

This is because when we run with `-n` the python program exits gracefully and everything is closed. Textual behaves a bit weirdly because it's being run through asyncio which takes over the control loop I believe, and something weird is happening. Look at the PR I made, that should fix the issue.

**Comment by mustafaquraish** [comment]
It seems that the issue had been fixed for a while when I made the fix, but for some reason I am getting the same error message again. I guess it might actually have something to do with `textual`. Weird.
