### ISSUE TITLE
Create panel to show full stacktrace

### ISSUE THREAD

**Issue by briancohan** [Perceptive-Porcupines/Perceptive-Porcupines-Code-Jam-8#64]
This could be either a modal that pops on top or a frame we can toggle on and off attached to the bottom.

`traceback.print_exception(type(RAISED_EXC), RAISED_EXC, RAISED_EXC.__traceback__)`

The `traceback` module might have some points on how to eliminate the added lines of the stacktrace generated by how we run the script.

https://docs.python.org/3/library/traceback.html

**Comment by mustafaquraish** [comment]
I was experimenting with this earlier, but it seems that on my machine whenever I try to add another `ScrollView()` panel into the DockView, everything starts getting really laggy and crashy. If I have 2 ScrollViews open and I try to press `Q` to close it takes ~5-10 seconds for the UI to actually close. 

I'm not 100% sure but it seems like this might be an issue in `textual` itself. Perhaps we can use a `Placeholder` or regular `Panel`, but It would be nice to be able to scroll if the exception is large. If anyone can try this out on their end and see if they get a similar issue that would be great (Just copy the definition of `self.body = ...` and insert the new ScrollView into the dock as well)

**Comment by briancohan** [comment]
I feel like the performance of textual varies greatly from execution to execution. But I think the user needs to be able to look at their traceback without having to quit the application to see it again.

**Comment by ethansocal** [comment]
Instead of creating a new ScrollView, we could assign a hotkey to switch the body to the traceback, such as `t`.

**Comment by mustafaquraish** [comment]
That could work. I think that's a pretty decent idea. Do you want to
implement it, or should I go ahead with it?
